encoder_features_0_0: true  # type: Conv2d
encoder_features_0_2: true # type: SiLU
encoder_features_1_0_block_0_0: true # type: Conv2d
encoder_features_1_0_block_0_2: true # type: SiLU
encoder_features_1_0_block_1_avgpool: true # type: AdaptiveAvgPool2d
encoder_features_1_0_block_1_fc1: true # type: Conv2d
encoder_features_1_0_block_1_activation: true # type: SiLU
encoder_features_1_0_block_1_fc2: true # type: Conv2d
encoder_features_1_0_block_1_scale_activation: true # type: Sigmoid
mul_0_f: true # type: mul
encoder_features_1_0_block_2_0: true # type: Conv2d
encoder_features_2_0_block_0_0: true # type: Conv2d
encoder_features_2_0_block_0_2: true # type: SiLU
encoder_features_2_0_block_1_0: true # type: Conv2d
encoder_features_2_0_block_1_2: true # type: SiLU
encoder_features_2_0_block_2_avgpool: true # type: AdaptiveAvgPool2d
encoder_features_2_0_block_2_fc1: true # type: Conv2d
encoder_features_2_0_block_2_activation: true # type: SiLU
encoder_features_2_0_block_2_fc2: true # type: Conv2d
encoder_features_2_0_block_2_scale_activation: true # type: Sigmoid
mul_1_f: true # type: mul
encoder_features_2_0_block_3_0: true # type: Conv2d
encoder_features_2_1_block_0_0: true # type: Conv2d
encoder_features_2_1_block_0_2: true # type: SiLU
encoder_features_2_1_block_1_0: true # type: Conv2d
encoder_features_2_1_block_1_2: true # type: SiLU
encoder_features_2_1_block_2_avgpool: true # type: AdaptiveAvgPool2d
encoder_features_2_1_block_2_fc1: true # type: Conv2d
encoder_features_2_1_block_2_activation: true # type: SiLU
encoder_features_2_1_block_2_fc2: true # type: Conv2d
encoder_features_2_1_block_2_scale_activation: true # type: Sigmoid
mul_2_f: true # type: mul
encoder_features_2_1_block_3_0: true # type: Conv2d
add_0_f: true # type: add
encoder_features_3_0_block_0_0: true # type: Conv2d
encoder_features_3_0_block_0_2: true # type: SiLU
encoder_features_3_0_block_1_0: true # type: Conv2d
encoder_features_3_0_block_1_2: true # type: SiLU
encoder_features_3_0_block_2_avgpool: true # type: AdaptiveAvgPool2d
encoder_features_3_0_block_2_fc1: true # type: Conv2d
encoder_features_3_0_block_2_activation: true # type: SiLU
encoder_features_3_0_block_2_fc2: true # type: Conv2d
encoder_features_3_0_block_2_scale_activation: true # type: Sigmoid
mul_3_f: true # type: mul
encoder_features_3_0_block_3_0: true # type: Conv2d
encoder_features_3_1_block_0_0: true # type: Conv2d
encoder_features_3_1_block_0_2: true # type: SiLU
encoder_features_3_1_block_1_0: true # type: Conv2d
encoder_features_3_1_block_1_2: true # type: SiLU
encoder_features_3_1_block_2_avgpool: true # type: AdaptiveAvgPool2d
encoder_features_3_1_block_2_fc1: true # type: Conv2d
encoder_features_3_1_block_2_activation: true # type: SiLU
encoder_features_3_1_block_2_fc2: true # type: Conv2d
encoder_features_3_1_block_2_scale_activation: true # type: Sigmoid
mul_4_f: true # type: mul
encoder_features_3_1_block_3_0: true # type: Conv2d
add_1_f: true # type: add
encoder_features_4_0_block_0_0: true # type: Conv2d
encoder_features_4_0_block_0_2: true # type: SiLU
encoder_features_4_0_block_1_0: true # type: Conv2d
encoder_features_4_0_block_1_2: true # type: SiLU
encoder_features_4_0_block_2_avgpool: true # type: AdaptiveAvgPool2d
encoder_features_4_0_block_2_fc1: true # type: Conv2d
encoder_features_4_0_block_2_activation: true # type: SiLU
encoder_features_4_0_block_2_fc2: true # type: Conv2d
encoder_features_4_0_block_2_scale_activation: true # type: Sigmoid
mul_5_f: true # type: mul
encoder_features_4_0_block_3_0: true # type: Conv2d
encoder_features_4_1_block_0_0: true # type: Conv2d
encoder_features_4_1_block_0_2: true # type: SiLU
encoder_features_4_1_block_1_0: true # type: Conv2d
encoder_features_4_1_block_1_2: true # type: SiLU
encoder_features_4_1_block_2_avgpool: true # type: AdaptiveAvgPool2d
encoder_features_4_1_block_2_fc1: true # type: Conv2d
encoder_features_4_1_block_2_activation: true # type: SiLU
encoder_features_4_1_block_2_fc2: true # type: Conv2d
encoder_features_4_1_block_2_scale_activation: true # type: Sigmoid
mul_6_f: true # type: mul
encoder_features_4_1_block_3_0: true # type: Conv2d
add_2_f: true # type: add
encoder_features_4_2_block_0_0: true # type: Conv2d
encoder_features_4_2_block_0_2: true # type: SiLU
encoder_features_4_2_block_1_0: true # type: Conv2d
encoder_features_4_2_block_1_2: true # type: SiLU
encoder_features_4_2_block_2_avgpool: true # type: AdaptiveAvgPool2d
encoder_features_4_2_block_2_fc1: true # type: Conv2d
encoder_features_4_2_block_2_activation: true # type: SiLU
encoder_features_4_2_block_2_fc2: true # type: Conv2d
encoder_features_4_2_block_2_scale_activation: true # type: Sigmoid
mul_7_f: true # type: mul
encoder_features_4_2_block_3_0: true # type: Conv2d
add_3_f: true # type: add
encoder_features_5_0_block_0_0: true # type: Conv2d
encoder_features_5_0_block_0_2: true # type: SiLU
encoder_features_5_0_block_1_0: true # type: Conv2d
encoder_features_5_0_block_1_2: true # type: SiLU
encoder_features_5_0_block_2_avgpool: true # type: AdaptiveAvgPool2d
encoder_features_5_0_block_2_fc1: true # type: Conv2d
encoder_features_5_0_block_2_activation: true # type: SiLU
encoder_features_5_0_block_2_fc2: true # type: Conv2d
encoder_features_5_0_block_2_scale_activation: true # type: Sigmoid
mul_8_f: true # type: mul
encoder_features_5_0_block_3_0: true # type: Conv2d
encoder_features_5_1_block_0_0: true # type: Conv2d
encoder_features_5_1_block_0_2: true # type: SiLU
encoder_features_5_1_block_1_0: true # type: Conv2d
encoder_features_5_1_block_1_2: true # type: SiLU
encoder_features_5_1_block_2_avgpool: true # type: AdaptiveAvgPool2d
encoder_features_5_1_block_2_fc1: true # type: Conv2d
encoder_features_5_1_block_2_activation: true # type: SiLU
encoder_features_5_1_block_2_fc2: true # type: Conv2d
encoder_features_5_1_block_2_scale_activation: true # type: Sigmoid
mul_9_f: true # type: mul
encoder_features_5_1_block_3_0: true # type: Conv2d
add_4_f: true # type: add
encoder_features_5_2_block_0_0: true # type: Conv2d
encoder_features_5_2_block_0_2: true # type: SiLU
encoder_features_5_2_block_1_0: true # type: Conv2d
encoder_features_5_2_block_1_2: true # type: SiLU
encoder_features_5_2_block_2_avgpool: true # type: AdaptiveAvgPool2d
encoder_features_5_2_block_2_fc1: true # type: Conv2d
encoder_features_5_2_block_2_activation: true # type: SiLU
encoder_features_5_2_block_2_fc2: true # type: Conv2d
encoder_features_5_2_block_2_scale_activation: true # type: Sigmoid
mul_10_f: true # type: mul
encoder_features_5_2_block_3_0: true # type: Conv2d
add_5_f: true # type: add
head_layers_0_adapter_conv_0_layers_0_0: true # type: (Conv2d, ReLU)
head_layers_0_adapter_conv_1_layers_0_0: true # type: (Conv2d, ReLU)
head_layers_0_adapter_conv_2_layers_0_0: true # type: (Conv2d, ReLU)
head_layers_0_adapter_conv_3_layers_0_0: true # type: (Conv2d, ReLU)
head_layers_1_fam_32_sm_layers_0_0: true # type: (Conv2d, ReLU)
head_layers_1_fam_32_up_layers_0_0: true # type: (Conv2d, ReLU)
interpolate_0_f: true # type: interpolate
add_6_f: true # type: add
head_layers_1_fam_16_sm_layers_0_0: true # type: (Conv2d, ReLU)
head_layers_1_fam_16_up_layers_0_0: true # type: (Conv2d, ReLU)
interpolate_1_f: true # type: interpolate
add_7_f: true # type: add
head_layers_1_fam_8_sm_layers_0_0: true # type: (Conv2d, ReLU)
head_layers_1_fam_8_up_layers_0_0: true # type: (Conv2d, ReLU)
interpolate_2_f: true # type: interpolate
add_8_f: true # type: add
head_layers_1_fam_4_layers_0_0: true # type: (Conv2d, ReLU)
interpolate_3_f: true # type: interpolate
cat_0_f: true # type: cat
interpolate_4_f: true # type: interpolate
cat_1_f: true # type: cat
interpolate_5_f: true # type: interpolate
cat_2_f: true # type: cat
head_layers_3_last_layer_0_0: true # type: (Conv2d, ReLU)
head_layers_3_last_layer_3: true # type: Conv2d
